// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomExercise = `-- name: CreateCustomExercise :one
INSERT INTO exercises (user_id, name, alternative_names, explanation, client_s)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, alternative_names, explanation, created_at, last_updated_at, client_s
`

type CreateCustomExerciseParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	Name             string      `json:"name"`
	AlternativeNames []string    `json:"alternative_names"`
	Explanation      pgtype.Text `json:"explanation"`
	ClientS          []byte      `json:"client_s"`
}

func (q *Queries) CreateCustomExercise(ctx context.Context, arg CreateCustomExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createCustomExercise,
		arg.UserID,
		arg.Name,
		arg.AlternativeNames,
		arg.Explanation,
		arg.ClientS,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AlternativeNames,
		&i.Explanation,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const createGlobalExercise = `-- name: CreateGlobalExercise :one
INSERT INTO exercises (name, alternative_names, explanation, client_s)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, alternative_names, explanation, created_at, last_updated_at, client_s
`

type CreateGlobalExerciseParams struct {
	Name             string      `json:"name"`
	AlternativeNames []string    `json:"alternative_names"`
	Explanation      pgtype.Text `json:"explanation"`
	ClientS          []byte      `json:"client_s"`
}

func (q *Queries) CreateGlobalExercise(ctx context.Context, arg CreateGlobalExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createGlobalExercise,
		arg.Name,
		arg.AlternativeNames,
		arg.Explanation,
		arg.ClientS,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AlternativeNames,
		&i.Explanation,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, user_id, name, alternative_names, explanation, created_at, last_updated_at, client_s FROM exercises WHERE id = $1
`

func (q *Queries) GetExerciseByID(ctx context.Context, id pgtype.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AlternativeNames,
		&i.Explanation,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const listExercisesForUser = `-- name: ListExercisesForUser :many
SELECT id, user_id, name, alternative_names, explanation, created_at, last_updated_at, client_s FROM exercises
WHERE user_id IS NULL OR user_id = $1
ORDER BY name
`

// Global exercises plus this user's own custom ones.
func (q *Queries) ListExercisesForUser(ctx context.Context, userID pgtype.UUID) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercisesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AlternativeNames,
			&i.Explanation,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ClientS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalExercises = `-- name: ListGlobalExercises :many
SELECT id, user_id, name, alternative_names, explanation, created_at, last_updated_at, client_s FROM exercises WHERE user_id IS NULL ORDER BY name
`

func (q *Queries) ListGlobalExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listGlobalExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AlternativeNames,
			&i.Explanation,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ClientS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
