// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID              string             `json:"id"`
	UserIDInAct     string             `json:"user_id_in_act"`
	SessionID       string             `json:"session_id"`
	ExerciseID      pgtype.Text        `json:"exercise_id"`
	ActivityType    string             `json:"activity_type"`
	Reps            pgtype.Int4        `json:"reps"`
	Weight          pgtype.Numeric     `json:"weight"`
	SortOrder       int32              `json:"sort_order"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	TotalTime       pgtype.Interval    `json:"total_time"`
	PerceivedEffort pgtype.Int4        `json:"perceived_effort"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastUpdatedAt   pgtype.Timestamptz `json:"last_updated_at"`
	ClientS         []byte             `json:"client_s"`
}

type AuthToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Exercise struct {
	ID               string             `json:"id"`
	UserID           pgtype.Text        `json:"user_id"`
	Name             string             `json:"name"`
	AlternativeNames []string           `json:"alternative_names"`
	Explanation      pgtype.Text        `json:"explanation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUpdatedAt    pgtype.Timestamptz `json:"last_updated_at"`
	ClientS          []byte             `json:"client_s"`
}

type Session struct {
	ID                     string             `json:"id"`
	UserID                 string             `json:"user_id"`
	SessionType            string             `json:"session_type"`
	StartTime              pgtype.Timestamptz `json:"start_time"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	TotalTime              pgtype.Interval    `json:"total_time"`
	TotalWeight            int32              `json:"total_weight"`
	OverallPerceivedEffort pgtype.Int4        `json:"overall_perceived_effort"`
	BurnedCals             pgtype.Int4        `json:"burned_cals"`
	UserNotes              pgtype.Text        `json:"user_notes"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	LastUpdatedAt          pgtype.Timestamptz `json:"last_updated_at"`
	ClientS                []byte             `json:"client_s"`
}

type User struct {
	ID            string             `json:"id"`
	Username      string             `json:"username"`
	DisplayName   string             `json:"display_name"`
	PasswordHash  string             `json:"password_hash"`
	Bio           pgtype.Text        `json:"bio"`
	Sex           pgtype.Text        `json:"sex"`
	Birthday      pgtype.Date        `json:"birthday"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastUpdatedAt pgtype.Timestamptz `json:"last_updated_at"`
	ClientS       []byte             `json:"client_s"`
}
