// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateCustomExercise(ctx context.Context, arg CreateCustomExerciseParams) (Exercise, error)
	CreateGlobalExercise(ctx context.Context, arg CreateGlobalExerciseParams) (Exercise, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes every activity belonging to any of the user's sessions. Needed
	// before deleting the user's custom exercises, since activities.exercise_id
	// is ON DELETE RESTRICT (to protect shared/global exercises from accidental
	// deletion) — that RESTRICT can otherwise conflict with the CASCADE from
	// users -> exercises during a single `DELETE FROM users`.
	DeleteActivitiesByUser(ctx context.Context, userID string) error
	DeleteAuthToken(ctx context.Context, tokenHash string) error
	// Deletes the user's own custom exercises. Must run after
	// DeleteActivitiesByUser so no activity still references them.
	DeleteExercisesByUser(ctx context.Context, userID pgtype.Text) error
	DeleteExpiredAuthTokens(ctx context.Context) error
	DeleteUser(ctx context.Context, id string) error
	GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error)
	GetExerciseByID(ctx context.Context, id string) (Exercise, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActivitiesBySession(ctx context.Context, sessionID string) ([]Activity, error)
	// Global exercises plus this user's own custom ones.
	ListExercisesForUser(ctx context.Context, userID pgtype.Text) ([]Exercise, error)
	ListGlobalExercises(ctx context.Context) ([]Exercise, error)
	ListSessionsByUser(ctx context.Context, userID string) ([]Session, error)
	RefreshAuthTokenExpiry(ctx context.Context, arg RefreshAuthTokenExpiryParams) error
}

var _ Querier = (*Queries)(nil)
