// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateCustomExercise(ctx context.Context, arg CreateCustomExerciseParams) (Exercise, error)
	CreateGlobalExercise(ctx context.Context, arg CreateGlobalExerciseParams) (Exercise, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetExerciseByID(ctx context.Context, id pgtype.UUID) (Exercise, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActivitiesBySession(ctx context.Context, sessionID pgtype.UUID) ([]Activity, error)
	// Global exercises plus this user's own custom ones.
	ListExercisesForUser(ctx context.Context, userID pgtype.UUID) ([]Exercise, error)
	ListGlobalExercises(ctx context.Context) ([]Exercise, error)
	ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error)
}

var _ Querier = (*Queries)(nil)
