// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    session_id, exercise_id, activity_type, reps, weight,
    sort_order, start_time, end_time, total_time, perceived_effort, client_s
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, session_id, exercise_id, activity_type, reps, weight, sort_order, start_time, end_time, total_time, perceived_effort, created_at, last_updated_at, client_s
`

type CreateActivityParams struct {
	SessionID       pgtype.UUID        `json:"session_id"`
	ExerciseID      pgtype.UUID        `json:"exercise_id"`
	ActivityType    string             `json:"activity_type"`
	Reps            pgtype.Int4        `json:"reps"`
	Weight          pgtype.Float4      `json:"weight"`
	SortOrder       int32              `json:"sort_order"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	TotalTime       pgtype.Interval    `json:"total_time"`
	PerceivedEffort pgtype.Int4        `json:"perceived_effort"`
	ClientS         []byte             `json:"client_s"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.SessionID,
		arg.ExerciseID,
		arg.ActivityType,
		arg.Reps,
		arg.Weight,
		arg.SortOrder,
		arg.StartTime,
		arg.EndTime,
		arg.TotalTime,
		arg.PerceivedEffort,
		arg.ClientS,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ActivityType,
		&i.Reps,
		&i.Weight,
		&i.SortOrder,
		&i.StartTime,
		&i.EndTime,
		&i.TotalTime,
		&i.PerceivedEffort,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, session_type, start_time, end_time,
    total_time, total_weight, overall_perceived_effort, burned_cals, user_notes, client_s
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, session_type, start_time, end_time, total_time, total_weight, overall_perceived_effort, burned_cals, user_notes, created_at, last_updated_at, client_s
`

type CreateSessionParams struct {
	UserID                 pgtype.UUID        `json:"user_id"`
	SessionType            string             `json:"session_type"`
	StartTime              pgtype.Timestamptz `json:"start_time"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	TotalTime              pgtype.Interval    `json:"total_time"`
	TotalWeight            int32              `json:"total_weight"`
	OverallPerceivedEffort pgtype.Int4        `json:"overall_perceived_effort"`
	BurnedCals             pgtype.Int4        `json:"burned_cals"`
	UserNotes              pgtype.Text        `json:"user_notes"`
	ClientS                []byte             `json:"client_s"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SessionType,
		arg.StartTime,
		arg.EndTime,
		arg.TotalTime,
		arg.TotalWeight,
		arg.OverallPerceivedEffort,
		arg.BurnedCals,
		arg.UserNotes,
		arg.ClientS,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionType,
		&i.StartTime,
		&i.EndTime,
		&i.TotalTime,
		&i.TotalWeight,
		&i.OverallPerceivedEffort,
		&i.BurnedCals,
		&i.UserNotes,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, session_type, start_time, end_time, total_time, total_weight, overall_perceived_effort, burned_cals, user_notes, created_at, last_updated_at, client_s FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionType,
		&i.StartTime,
		&i.EndTime,
		&i.TotalTime,
		&i.TotalWeight,
		&i.OverallPerceivedEffort,
		&i.BurnedCals,
		&i.UserNotes,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const listActivitiesBySession = `-- name: ListActivitiesBySession :many
SELECT id, session_id, exercise_id, activity_type, reps, weight, sort_order, start_time, end_time, total_time, perceived_effort, created_at, last_updated_at, client_s FROM activities WHERE session_id = $1 ORDER BY sort_order
`

func (q *Queries) ListActivitiesBySession(ctx context.Context, sessionID pgtype.UUID) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.ActivityType,
			&i.Reps,
			&i.Weight,
			&i.SortOrder,
			&i.StartTime,
			&i.EndTime,
			&i.TotalTime,
			&i.PerceivedEffort,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ClientS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, session_type, start_time, end_time, total_time, total_weight, overall_perceived_effort, burned_cals, user_notes, created_at, last_updated_at, client_s FROM sessions WHERE user_id = $1 ORDER BY start_time DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionType,
			&i.StartTime,
			&i.EndTime,
			&i.TotalTime,
			&i.TotalWeight,
			&i.OverallPerceivedEffort,
			&i.BurnedCals,
			&i.UserNotes,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ClientS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
