// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, bio, sex, birthday, created_at, last_updated_at, client_s)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, username, display_name, password_hash, bio, sex, birthday, created_at, last_updated_at, client_s
`

type CreateUserParams struct {
	Username      string             `json:"username"`
	DisplayName   string             `json:"display_name"`
	PasswordHash  string             `json:"password_hash"`
	Bio           pgtype.Text        `json:"bio"`
	Sex           pgtype.Text        `json:"sex"`
	Birthday      pgtype.Date        `json:"birthday"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastUpdatedAt pgtype.Timestamptz `json:"last_updated_at"`
	ClientS       []byte             `json:"client_s"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Bio,
		arg.Sex,
		arg.Birthday,
		arg.CreatedAt,
		arg.LastUpdatedAt,
		arg.ClientS,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Bio,
		&i.Sex,
		&i.Birthday,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const deleteActivitiesByUser = `-- name: DeleteActivitiesByUser :exec
DELETE FROM activities
WHERE session_id IN (SELECT id FROM sessions WHERE user_id = $1)
`

// Deletes every activity belonging to any of the user's sessions. Needed
// before deleting the user's custom exercises, since activities.exercise_id
// is ON DELETE RESTRICT (to protect shared/global exercises from accidental
// deletion) — that RESTRICT can otherwise conflict with the CASCADE from
// users -> exercises during a single `DELETE FROM users`.
func (q *Queries) DeleteActivitiesByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteActivitiesByUser, userID)
	return err
}

const deleteExercisesByUser = `-- name: DeleteExercisesByUser :exec
DELETE FROM exercises WHERE user_id = $1
`

// Deletes the user's own custom exercises. Must run after
// DeleteActivitiesByUser so no activity still references them.
func (q *Queries) DeleteExercisesByUser(ctx context.Context, userID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteExercisesByUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, bio, sex, birthday, created_at, last_updated_at, client_s FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Bio,
		&i.Sex,
		&i.Birthday,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, bio, sex, birthday, created_at, last_updated_at, client_s FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Bio,
		&i.Sex,
		&i.Birthday,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}

const updatePasswordHashByID = `-- name: UpdatePasswordHashByID :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdatePasswordHashByIDParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHashByID(ctx context.Context, arg UpdatePasswordHashByIDParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHashByID, arg.ID, arg.PasswordHash)
	return err
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
SET (username, display_name, bio, sex, birthday, last_updated_at, client_s) = ($2, $3, $4, $5, $6, $7, $8)
WHERE id = $1
RETURNING id, username, display_name, password_hash, bio, sex, birthday, created_at, last_updated_at, client_s
`

type UpdateUserByIDParams struct {
	ID            string             `json:"id"`
	Username      string             `json:"username"`
	DisplayName   string             `json:"display_name"`
	Bio           pgtype.Text        `json:"bio"`
	Sex           pgtype.Text        `json:"sex"`
	Birthday      pgtype.Date        `json:"birthday"`
	LastUpdatedAt pgtype.Timestamptz `json:"last_updated_at"`
	ClientS       []byte             `json:"client_s"`
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserByID,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.Sex,
		arg.Birthday,
		arg.LastUpdatedAt,
		arg.ClientS,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Bio,
		&i.Sex,
		&i.Birthday,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ClientS,
	)
	return i, err
}
